var p=Object.defineProperty;var y=(s,e,r)=>e in s?p(s,e,{enumerable:!0,configurable:!0,writable:!0,value:r}):s[e]=r;var u=(s,e,r)=>(y(s,typeof e!="symbol"?e+"":e,r),r);import{S as f,a as g,i as v}from"./assets/vendor-5401a4b0.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function r(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=r(t);fetch(t.href,o)}})();const w=document.querySelector(".gallery"),x=document.querySelector(".loader");function h(s){x.setAttribute("hidden","");const e=s.map(a=>`<li class="gallery-item">
		   <a class="gallery-link" href=${a.largeImageURL}>
			   <img class="gallery-image" src=${a.webformatURL} alt="${a.tags}" />
		   </a>
		   <div class="container">
			   <div class="container-text"><h3 class="titel-text">Likes</h3><p class="text">${a.likes}</p></div>
			   <div class="container-text"><h3 class="titel-text">Views</h3><p class="text">${a.views}</p></div>
			   <div class="container-text"><h3 class="titel-text">Comments</h3><p class="text">${a.comments}</p></div>
			   <div class="container-text"><h3 class="titel-text">Dowloads</h3><p class="text">${a.downloads}</p></div>
		   </div>
	   </li>`).join("");w.insertAdjacentHTML("beforeend",e),new f(".gallery-link",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}).refresh()}const n=class n{constructor(){this.BASE_URL="https://pixabay.com/api/",this.query=null,this.page=1,this.totalResult=0}async getInfoArticles(){const e={key:"42169950-0e8cca4ed1d3fcef898dec13a",q:this.query,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:n.PAGE_SIZE,page:this.page};return await g.get(`${this.BASE_URL}`,{params:e}).then(r=>{try{return r.data}catch{console.log(Error.message)}})}};u(n,"PAGE_SIZE",15);let c=n;const d=document.querySelector(".js-form"),L=document.querySelector(".gallery"),S=document.querySelector(".loader"),m=document.querySelector(".js-load-more"),i=new c;d.addEventListener("submit",q);m.addEventListener("click",b);async function q(s){s.preventDefault();const e=d.elements.text.value.trim();if(d.elements.text.value="",S.removeAttribute("hidden"),L.innerHTML="",e){i.page=1,i.query=e;const r=await i.getInfoArticles(e);h(r.hits),m.classList.remove("visually-hidden")}else v.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})}async function b(){{i.page+=1;const s=await i.getInfoArticles();h(s.hits);const r=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r.width*2,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
